### PR TITLE
Week 2: Simulating blockflix

### PR DESCRIPTION
**Pull request by mikeghen**

### CODE REVIEW

**Comment by pdamodaran** [comment]
I pulled the latest code and attempted to run "flask seed" but got an error - No such command "seed".  i have probably missed some steps but can't figure out what they are.  Could you let me know how to fix this?

**Comment by pdamodaran** [comment]
Never mind - it turns out that I ran into the error because I had not installed the new libraries.  Once I installed the libraries, I was able to run the command.

**Comment by pdamodaran** [comment]
Mike - did you apply pre-processing/cleaning to the credits.csv file?  I ran into the following error:

sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1366, "Incorrect string value: '\\xC4\\x81d' for column 'last_name' at row 1321")

**Comment by mikeghen** [comment]
@pdamodaran, did you make sure to checkout this branch? `git checkout feature/simulation`

**Comment by mikeghen** [comment]
@pdamodaran, I did not do any preprocessing. Are you on Windows? Did you open the file in any other system (like excel) and resave it? Look into opening up CSV's with encodings in Python. That looks like unicode or something.

**Comment by pdamodaran** [comment]
@mikeghen - I am on a mac.  I downloaded the files from the kaggle website that you had shown us and put them in the data location.  

I did some digging into the error and someone suggested I do the following to fix the error:

e = create_engine(
    "mysql+pymysql://username@hostname?charset=utf8mb4")

Does that sound right?  If so, where should I add it?

**Comment by mikeghen** [comment]
That sounds like something that could work but I don't think that's needed, you would want to look in `settings.py` to make that change. Try deleting the files and downloading them again too

**Comment by mikeghen** [comment]
@pdamodaran That sounds like something that could work but I don't think that's needed, you would want to look in settings.py to make that change. Try deleting the files and downloading them again too.

**Pull request merged**
